### ISSUE TITLE
Create an input hash on MainState to be accessible during update calls

### ISSUE THREAD

**Issue by nafarlee** [distal-designs/bones-quest#2]
ggez handles inputs via overloaded event handlers on things like key up, key down, etc...

To allow our update calls to have access to the current inputs (and perhaps the previous ones!), we need to have some data structure that contains the inputs on MainState.

**Comment by nafarlee** [comment]
Any status on this @MoonWatcher582 ?

**Comment by MoonWatcher582** [comment]
@nafarlee I started up on this a couple of days ago but came up with a slightly different design yesterday. Should be able to take care of most of this today and complete by Tuesday/Wednesday.

**Comment by nafarlee** [comment]
Closed by #40

**Comment by nafarlee** [comment]
Closed by #40
