### ISSUE TITLE
Visual Novel Engine Features

### ISSUE THREAD

**Issue by cjohnwilkinson** [distal-designs/bones-quest#30]
- [ ] Folder tab with name, above text box to the top left (Max characters for a name? Probably 20)
- [ ] Non-active portraits are darkened, DKC2 style
- [ ] Reposition portraits around the screen (set of points, -50 to 50)
- [ ] Ability to change facing of portraits (Left, right)

**Comment by nafarlee** [comment]
This issue lives on individually as issues #52, #51, #50, #49, and #48.
As such, this issue will be closed.
